name: Gestart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_share: ^1.0.5
  string_validator: ^0.1.4
  path_provider: ^1.6.27
  flutter_icons: ^1.1.0
  flutter_screenutil: ^4.0.3+1
  google_fonts: ^1.1.1
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_plugin_pdf_viewer: ^1.0.7
  barcode: ^1.17.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

  #notificações
  firebase_messaging: ^7.0.3

  # Validators
  cpfcnpj: ^1.0.3

  # Mask
  easy_mask: ^1.1.5

  # Images
  image_picker: ^0.6.7+17
  image_cropper: ^1.3.1

  # Widgets
  time_picker_widget: ^1.0.0+9

  # Routes, Dependence Injection, Service Locator
  flutter_modular: ^2.0.1
  injectable: ^1.0.5
  get_it: ^5.0.3

  # charts
  charts_flutter: ^0.10.0

  # Storage
  shared_preferences: ^0.5.12+4

  package_info: ^0.4.3+2
  share: ^0.6.5+4
  url_launcher: ^5.7.10
  table_calendar: ^2.3.3
  
  interval_time_picker: "^0.1.0" 

  mask_text_input_formatter: "1.2.1"

  android_path_provider: ^0.1.1 #buscar diretorio de download
  open_file: ^3.0.3 #abrir arquivos
  permission_handler: ^5.1.0+2 #verificar e solicitar permissoes
  speech_to_text: ^3.2.0 #converter voz em texto
  avatar_glow: ^1.2.0 #animações
  string_similarity: ^1.1.0 #comparar strings

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.1
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/_icon.png"

flutter:
  assets:
    - assets/images/
    - assets/icon/
    
  uses-material-design: true



 