name: Gestart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_share: ^2.0.0 
  string_validator: ^0.3.0 
  path_provider: ^2.0.4 
  flutter_screenutil: ^5.2.0 
  google_fonts: 2.2.0 
  dio: ^4.0.4 
  flutter_mobx: ^2.0.4 
  mobx: ^2.0.6+1 
  barcode: ^2.1.0 

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0 
  line_icons: ^2.0.1 

  

  # Mask
  easy_mask: ^2.0.1 

  # Images
  image_picker: ^0.8.4+1 
  image_cropper: ^1.4.1 

  # Widgets
  time_picker_widget: ^1.0.0+10 

  # Routes, Dependence Injection, Service Locator
  flutter_modular: ^4.4.0+1 
  injectable: ^1.5.3 
  get_it: ^7.2.0 

  # charts
  charts_flutter: ^0.11.0 

  # Storage
  shared_preferences: ^2.0.7 

  package_info: ^2.0.2
  share: ^2.0.4 
  url_launcher: ^6.0.10 
  table_calendar: ^3.0.3 
  
  interval_time_picker: ^1.0.0+3 

  mask_text_input_formatter: ^2.1.0 

  android_path_provider: ^0.3.0  #buscar diretorio de download
  open_file: ^3.2.1  #abrir arquivos
  permission_handler: ^8.1.6  #verificar e solicitar permissoes
  speech_to_text: ^5.4.3  #converter voz em texto
  avatar_glow: ^2.0.2  #animações
  string_similarity: ^2.0.0  #comparar strings
  flutter_local_notifications: ^9.3.1 
  firebase_messaging: ^11.2.6
 

dev_dependencies:
  mockito: ^5.0.15 
  modular_codegen: ^3.0.2 
  mobx_codegen: ^2.0.2 
  build_runner: ^2.1.2 
  firebase_core: ^1.12.0 
  flutter_launcher_icons: ^0.9.2 


flutter:
  assets:
    - assets/images/
    - assets/images/bg-green.old.jpg
    - assets/images/home.png
    - assets/icon/
    - assets/images/logo.png
    
  uses-material-design: true



 